GET http://localhost:3000/api/courses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzci14eGQ5cGxfVl9Nc18iLCJpYXQiOjE2NzkwMjY4NTAsImV4cCI6MTY3OTAyNjg2NX0.FY0-r2AOq9R20igWjeT7r_TSM8PRaj2SW03B-TAujGY

### 
POST http://localhost:3000/api/authentication
Content-Type: application/json

{
  "email": "hokky@undiksha.ac.id",
  "password": "123" 
}

###
PUT http://localhost:3000/api/authentication
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzci14eGQ5cGxfVl9Nc18iLCJpYXQiOjE2NzkwMjY3OTksImV4cCI6MTY3OTExMzE5OX0.aGdbmnCWQBzQagptTOq4tyUiNWNcOcpwPzNTcLt4d3Q"
}

### 
DELETE http://localhost:3000/api/authentication
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzci14eGQ5cGxfVl9Nc18iLCJpYXQiOjE2NzkwMjY4NTAsImV4cCI6MTY3OTAyNjg2NX0.FY0-r2AOq9R20igWjeT7r_TSM8PRaj2SW03B-TAujGY"
}

### PAYMENT
POST http://localhost:3000/api/payments
Content-Type: application/json

{
  "amount": 800000,
  "payerEmail": "hokky@undiksha.ac.id",
  "description": "Pembayaran Produk ABC"
}